### ISSUE TITLE
Question on changes to the existing repositories

### ISSUE THREAD

**Issue by andismith** [shopsys/monorepo-tools#1]
I would like to trial and demo what a monorepo would look like for us, get internal agreement and then at a later date (if I get the go ahead) run the command again from scratch with the latest changes?

Does running `monorepo_build.sh` edit my existing repositories in any way, or are all changes to files and history only made on the new monorepo itself?

Thanks

**Comment by PetrHeinz** [comment]
Hello @andismith,

the `monorepo_build.sh` does not modify original repositories in any way. You should create an empty repository first and that is the only one that will be affected by the build process. It will contain all branches of the first repository and master branches of all other repos.

The `monorepo_split.sh` will push the split repositories into the master branch of all original repos. It should be also safe to use if you do not commit any modifications into the monorepo as it does not force push.

**Comment by andismith** [comment]
Perfect! Thank you!
